type AspectRatio = "aspect-auto"
| "aspect-square"
| "aspect-video"

type column = "columns-1"
| "columns-2"
| "columns-3"
| "columns-4"
| "columns-5"
| "columns-6"
| "columns-7"
| "columns-8"
| "columns-9"
| "columns-10"
| "columns-11"
| "columns-12"
| "columns-auto"
| "columns-3xs"
| "columns-2xs"
| "columns-xs"
| "columns-sm"
| "columns-md"
| "columns-lg"
| "columns-xl"
| "columns-2xl"
| "columns-3xl"
| "columns-4xl"
| "columns-5xl"
| "columns-6xl"
| "columns-7xl"

type gap = "gap-x-0"
| "gap-x-px"
| "gap-x-0.5"
| "gap-x-1"
| "gap-x-1.5"
| "gap-x-2"
| "gap-x-2.5"
| "gap-x-3"
| "gap-x-3.5"
| "gap-x-4"
| "gap-x-5"
| "gap-x-6"
| "gap-x-7"
| "gap-x-8"
| "gap-x-9"
| "gap-x-10"
| "gap-x-11"
| "gap-x-12"
| "gap-x-14"
| "gap-x-16"
| "gap-x-20"
| "gap-x-24"
| "gap-x-28"
| "gap-x-32"
| "gap-x-36"
| "gap-x-40"
| "gap-x-44"
| "gap-x-48"
| "gap-x-52"
| "gap-x-56"
| "gap-x-60"
| "gap-x-64"
| "gap-x-72"
| "gap-x-80"
| "gap-x-96"

type span = "col-span-1"
| "col-span-2"
| "col-span-3"
| "col-span-4"
| "col-span-5"
| "col-span-6"
| "col-span-7"
| "col-span-8"
| "col-span-9"
| "col-span-10"
| "col-span-11"
| "col-span-12"
| "col-span-full"
| "col-auto"

type colStart = "col-start-1"
| "col-start-2"
| "col-start-3"
| "col-start-4"
| "col-start-5"
| "col-start-6"
| "col-start-7"
| "col-start-8"
| "col-start-9"
| "col-start-10"
| "col-start-11"
| "col-start-12"
| "col-start-13"
| "col-start-auto"

type colEnd = "col-end-1"
| "col-end-2"
| "col-end-3"
| "col-end-4"
| "col-end-5"
| "col-end-6"
| "col-end-7"
| "col-end-8"
| "col-end-9"
| "col-end-10"
| "col-end-11"
| "col-end-12"
| "col-end-13"
| "col-end-auto"

type breakAfter = "break-after-auto"
| "break-after-avoid"
| "break-after-all"
| "break-after-avoid-page"
| "break-after-page"
| "break-after-left"
| "break-after-right"
| "break-after-column"

type breakBefore = "break-before-auto"
| "break-before-avoid"
| "break-before-all"
| "break-before-avoid-page"
| "break-before-page"
| "break-before-left"
| "break-before-right"
| "break-before-column"

type breakInside = "break-inside-auto"
| "break-inside-avoid"
| "break-inside-avoid-page"
| "break-inside-avoid-column"